/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { DrinkType, DrinkType$inboundSchema } from "./drinktype.js";

export type Drink = {
  /**
   * The name of the drink.
   */
  name: string;
  /**
   * The price of one unit of the drink in US cents.
   */
  price: number;
  /**
   * The product code of the drink, only available when authenticated.
   */
  productCode?: string | undefined;
  /**
   * The number of units of the drink in stock, only available when authenticated.
   */
  stock?: number | undefined;
  /**
   * The type of drink.
   */
  type?: DrinkType | undefined;
  /**
   * The volume of the drink in milliliters.
   */
  volume?: number | undefined;
};

/** @internal */
export const Drink$inboundSchema: z.ZodType<Drink, z.ZodTypeDef, unknown> = z
  .object({
    name: z.string(),
    price: z.number(),
    productCode: z.string().optional(),
    stock: z.number().int().optional(),
    type: DrinkType$inboundSchema.optional(),
    volume: z.number().int().optional(),
  });

export function drinkFromJSON(
  jsonString: string,
): SafeParseResult<Drink, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Drink$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Drink' from JSON`,
  );
}
