/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * The type of drink.
 */
export enum DrinkType {
  Cocktail = "cocktail",
  NonAlcoholic = "non-alcoholic",
  Beer = "beer",
  Wine = "wine",
  Spirit = "spirit",
  Other = "other",
}

/** @internal */
export const DrinkType$inboundSchema: z.ZodNativeEnum<typeof DrinkType> = z
  .nativeEnum(DrinkType);
/** @internal */
export const DrinkType$outboundSchema: z.ZodNativeEnum<typeof DrinkType> =
  DrinkType$inboundSchema;
