/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * The type of order.
 */
export enum OrderType {
  Drink = "drink",
  Ingredient = "ingredient",
}

/** @internal */
export const OrderType$inboundSchema: z.ZodNativeEnum<typeof OrderType> = z
  .nativeEnum(OrderType);
/** @internal */
export const OrderType$outboundSchema: z.ZodNativeEnum<typeof OrderType> =
  OrderType$inboundSchema;
