/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { OrderType, OrderType$outboundSchema } from "./ordertype.js";

/**
 * An order for a drink or ingredient.
 */
export type OrderInput = {
  /**
   * The product code of the drink or ingredient.
   */
  productCode: string;
  /**
   * The number of units of the drink or ingredient to order.
   */
  quantity: number;
  /**
   * The type of order.
   */
  type: OrderType;
};

/** @internal */
export type OrderInput$Outbound = {
  productCode: string;
  quantity: number;
  type: string;
};

/** @internal */
export const OrderInput$outboundSchema: z.ZodType<
  OrderInput$Outbound,
  z.ZodTypeDef,
  OrderInput
> = z.object({
  productCode: z.string(),
  quantity: z.number().int(),
  type: OrderType$outboundSchema,
});

export function orderInputToJSON(orderInput: OrderInput): string {
  return JSON.stringify(OrderInput$outboundSchema.parse(orderInput));
}
