/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  OrderType,
  OrderType$inboundSchema,
  OrderType$outboundSchema,
} from "./ordertype.js";

/**
 * An order for a drink or ingredient.
 */
export type OrderInput = {
  /**
   * The product code of the drink or ingredient.
   */
  productCode: string;
  /**
   * The number of units of the drink or ingredient to order.
   */
  quantity: number;
  /**
   * The type of order.
   */
  type: OrderType;
};

/** @internal */
export const OrderInput$inboundSchema: z.ZodType<
  OrderInput,
  z.ZodTypeDef,
  unknown
> = z.object({
  productCode: z.string(),
  quantity: z.number().int(),
  type: OrderType$inboundSchema,
});
/** @internal */
export type OrderInput$Outbound = {
  productCode: string;
  quantity: number;
  type: string;
};

/** @internal */
export const OrderInput$outboundSchema: z.ZodType<
  OrderInput$Outbound,
  z.ZodTypeDef,
  OrderInput
> = z.object({
  productCode: z.string(),
  quantity: z.number().int(),
  type: OrderType$outboundSchema,
});

export function orderInputToJSON(orderInput: OrderInput): string {
  return JSON.stringify(OrderInput$outboundSchema.parse(orderInput));
}
export function orderInputFromJSON(
  jsonString: string,
): SafeParseResult<OrderInput, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrderInput$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrderInput' from JSON`,
  );
}
