/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { BarSDKError } from "./barsdkerror.js";

/**
 * An error occurred interacting with the API.
 */
export type APIErrorData = {
  code?: string | undefined;
  details?: { [k: string]: any } | undefined;
  message?: string | undefined;
};

/**
 * An error occurred interacting with the API.
 */
export class APIError extends BarSDKError {
  code?: string | undefined;
  details?: { [k: string]: any } | undefined;

  /** The original data that was passed to this error instance. */
  data$: APIErrorData;

  constructor(
    err: APIErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.code != null) this.code = err.code;
    if (err.details != null) this.details = err.details;

    this.name = "APIError";
  }
}

/** @internal */
export const APIError$inboundSchema: z.ZodType<
  APIError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string().optional(),
  details: z.record(z.any()).optional(),
  message: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new APIError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
