/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type AuthenticateRequestBody = {
  password?: string | undefined;
  username?: string | undefined;
};

/**
 * The api key to use for authenticated endpoints.
 */
export type AuthenticateResponseBody = {
  token?: string | undefined;
};

export type AuthenticateResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * An unknown error occurred interacting with the API.
   */
  error?: shared.ErrorT | undefined;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * The api key to use for authenticated endpoints.
   */
  object?: AuthenticateResponseBody | undefined;
};

/** @internal */
export type AuthenticateRequestBody$Outbound = {
  password?: string | undefined;
  username?: string | undefined;
};

/** @internal */
export const AuthenticateRequestBody$outboundSchema: z.ZodType<
  AuthenticateRequestBody$Outbound,
  z.ZodTypeDef,
  AuthenticateRequestBody
> = z.object({
  password: z.string().optional(),
  username: z.string().optional(),
});

export function authenticateRequestBodyToJSON(
  authenticateRequestBody: AuthenticateRequestBody,
): string {
  return JSON.stringify(
    AuthenticateRequestBody$outboundSchema.parse(authenticateRequestBody),
  );
}

/** @internal */
export const AuthenticateResponseBody$inboundSchema: z.ZodType<
  AuthenticateResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  token: z.string().optional(),
});

export function authenticateResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<AuthenticateResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthenticateResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthenticateResponseBody' from JSON`,
  );
}

/** @internal */
export const AuthenticateResponse$inboundSchema: z.ZodType<
  AuthenticateResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  Error: shared.ErrorT$inboundSchema.optional(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
  object: z.lazy(() => AuthenticateResponseBody$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "Error": "error",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
  });
});

export function authenticateResponseFromJSON(
  jsonString: string,
): SafeParseResult<AuthenticateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthenticateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthenticateResponse' from JSON`,
  );
}
