/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type CreateOrderRequest = {
  requestBody: Array<shared.OrderInput>;
  /**
   * The url to call when the order is updated.
   */
  callbackUrl?: string | undefined;
};

export type CreateOrderResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * An unknown error occurred interacting with the API.
   */
  error?: shared.ErrorT | undefined;
  /**
   * The order was created successfully.
   */
  order?: shared.Order | undefined;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
};

/** @internal */
export type CreateOrderRequest$Outbound = {
  RequestBody: Array<shared.OrderInput$Outbound>;
  callback_url?: string | undefined;
};

/** @internal */
export const CreateOrderRequest$outboundSchema: z.ZodType<
  CreateOrderRequest$Outbound,
  z.ZodTypeDef,
  CreateOrderRequest
> = z.object({
  requestBody: z.array(shared.OrderInput$outboundSchema),
  callbackUrl: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
    callbackUrl: "callback_url",
  });
});

export function createOrderRequestToJSON(
  createOrderRequest: CreateOrderRequest,
): string {
  return JSON.stringify(
    CreateOrderRequest$outboundSchema.parse(createOrderRequest),
  );
}

/** @internal */
export const CreateOrderResponse$inboundSchema: z.ZodType<
  CreateOrderResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  Error: shared.ErrorT$inboundSchema.optional(),
  Order: shared.Order$inboundSchema.optional(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "Error": "error",
    "Order": "order",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
  });
});

export function createOrderResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateOrderResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateOrderResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateOrderResponse' from JSON`,
  );
}
