/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type GetDrinkRequest = {
  name: string;
};

export type GetDrinkResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * A drink.
   */
  drink?: shared.Drink | undefined;
  /**
   * An unknown error occurred interacting with the API.
   */
  error?: shared.ErrorT | undefined;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
};

/** @internal */
export type GetDrinkRequest$Outbound = {
  name: string;
};

/** @internal */
export const GetDrinkRequest$outboundSchema: z.ZodType<
  GetDrinkRequest$Outbound,
  z.ZodTypeDef,
  GetDrinkRequest
> = z.object({
  name: z.string(),
});

export function getDrinkRequestToJSON(
  getDrinkRequest: GetDrinkRequest,
): string {
  return JSON.stringify(GetDrinkRequest$outboundSchema.parse(getDrinkRequest));
}

/** @internal */
export const GetDrinkResponse$inboundSchema: z.ZodType<
  GetDrinkResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  Drink: shared.Drink$inboundSchema.optional(),
  Error: shared.ErrorT$inboundSchema.optional(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "Drink": "drink",
    "Error": "error",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
  });
});

export function getDrinkResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetDrinkResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetDrinkResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetDrinkResponse' from JSON`,
  );
}
