/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type GetFoodRequest = {
  name: string;
};

/**
 * A food item.
 */
export type GetFoodResponseBody = {
  name?: string | undefined;
};

export type GetFoodResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * An unknown error occurred interacting with the API.
   */
  error?: shared.ErrorT | undefined;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * A food item.
   */
  object?: GetFoodResponseBody | undefined;
};

/** @internal */
export type GetFoodRequest$Outbound = {
  name: string;
};

/** @internal */
export const GetFoodRequest$outboundSchema: z.ZodType<
  GetFoodRequest$Outbound,
  z.ZodTypeDef,
  GetFoodRequest
> = z.object({
  name: z.string(),
});

export function getFoodRequestToJSON(getFoodRequest: GetFoodRequest): string {
  return JSON.stringify(GetFoodRequest$outboundSchema.parse(getFoodRequest));
}

/** @internal */
export const GetFoodResponseBody$inboundSchema: z.ZodType<
  GetFoodResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string().optional(),
});

export function getFoodResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetFoodResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetFoodResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetFoodResponseBody' from JSON`,
  );
}

/** @internal */
export const GetFoodResponse$inboundSchema: z.ZodType<
  GetFoodResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  Error: shared.ErrorT$inboundSchema.optional(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
  object: z.lazy(() => GetFoodResponseBody$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "Error": "error",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
  });
});

export function getFoodResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetFoodResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetFoodResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetFoodResponse' from JSON`,
  );
}
