/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type ListIngredientsRequest = {
  /**
   * A list of ingredients to filter by. If not provided all ingredients will be returned.
   */
  ingredients?: Array<string> | undefined;
  page: number;
};

export type Data = {
  resultArray: Array<number>;
};

/**
 * A list of ingredients.
 */
export type ListIngredientsResponseBody = {
  data?: Data | undefined;
};

export type ListIngredientsResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * An unknown error occurred interacting with the API.
   */
  error?: shared.ErrorT | undefined;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * A list of ingredients.
   */
  object?: ListIngredientsResponseBody | undefined;
};

/** @internal */
export type ListIngredientsRequest$Outbound = {
  ingredients?: Array<string> | undefined;
  page: number;
};

/** @internal */
export const ListIngredientsRequest$outboundSchema: z.ZodType<
  ListIngredientsRequest$Outbound,
  z.ZodTypeDef,
  ListIngredientsRequest
> = z.object({
  ingredients: z.array(z.string()).optional(),
  page: z.number().int(),
});

export function listIngredientsRequestToJSON(
  listIngredientsRequest: ListIngredientsRequest,
): string {
  return JSON.stringify(
    ListIngredientsRequest$outboundSchema.parse(listIngredientsRequest),
  );
}

/** @internal */
export const Data$inboundSchema: z.ZodType<Data, z.ZodTypeDef, unknown> = z
  .object({
    resultArray: z.array(z.number().int()),
  });

export function dataFromJSON(
  jsonString: string,
): SafeParseResult<Data, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Data$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Data' from JSON`,
  );
}

/** @internal */
export const ListIngredientsResponseBody$inboundSchema: z.ZodType<
  ListIngredientsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => Data$inboundSchema).optional(),
});

export function listIngredientsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListIngredientsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListIngredientsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListIngredientsResponseBody' from JSON`,
  );
}

/** @internal */
export const ListIngredientsResponse$inboundSchema: z.ZodType<
  ListIngredientsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  Error: shared.ErrorT$inboundSchema.optional(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
  object: z.lazy(() => ListIngredientsResponseBody$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "Error": "error",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
  });
});

export function listIngredientsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListIngredientsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListIngredientsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListIngredientsResponse' from JSON`,
  );
}
