/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type ListDrinksRequest = {
  /**
   * The type of drink to filter by. If not provided all drinks will be returned.
   */
  drinkType?: shared.DrinkType | undefined;
};

export type ListDrinksResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * An unknown error occurred interacting with the API.
   */
  error?: shared.ErrorT | undefined;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * A list of drinks.
   */
  classes?: Array<shared.Drink> | undefined;
};

/** @internal */
export type ListDrinksRequest$Outbound = {
  drinkType?: string | undefined;
};

/** @internal */
export const ListDrinksRequest$outboundSchema: z.ZodType<
  ListDrinksRequest$Outbound,
  z.ZodTypeDef,
  ListDrinksRequest
> = z.object({
  drinkType: shared.DrinkType$outboundSchema.optional(),
});

export function listDrinksRequestToJSON(
  listDrinksRequest: ListDrinksRequest,
): string {
  return JSON.stringify(
    ListDrinksRequest$outboundSchema.parse(listDrinksRequest),
  );
}

/** @internal */
export const ListDrinksResponse$inboundSchema: z.ZodType<
  ListDrinksResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  Error: shared.ErrorT$inboundSchema.optional(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
  classes: z.array(shared.Drink$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "Error": "error",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
  });
});

export function listDrinksResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListDrinksResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListDrinksResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListDrinksResponse' from JSON`,
  );
}
