/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

/**
 * A list of food items.
 */
export type ListFoodsResponseBody = {
  name?: string | undefined;
};

export type ListFoodsResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * An unknown error occurred interacting with the API.
   */
  error?: shared.ErrorT | undefined;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * A list of food items.
   */
  object?: ListFoodsResponseBody | undefined;
};

/** @internal */
export const ListFoodsResponseBody$inboundSchema: z.ZodType<
  ListFoodsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string().optional(),
});

export function listFoodsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListFoodsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListFoodsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListFoodsResponseBody' from JSON`,
  );
}

/** @internal */
export const ListFoodsResponse$inboundSchema: z.ZodType<
  ListFoodsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  Error: shared.ErrorT$inboundSchema.optional(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
  object: z.lazy(() => ListFoodsResponseBody$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "Error": "error",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
  });
});

export function listFoodsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListFoodsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListFoodsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListFoodsResponse' from JSON`,
  );
}
