/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export enum Webhook {
  StockUpdate = "stockUpdate",
}

export type RequestBody = {
  url?: string | undefined;
  webhook?: Webhook | undefined;
};

export type SubscribeToWebhooksResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * An unknown error occurred interacting with the API.
   */
  error?: shared.ErrorT | undefined;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
};

/** @internal */
export const Webhook$outboundSchema: z.ZodNativeEnum<typeof Webhook> = z
  .nativeEnum(Webhook);

/** @internal */
export type RequestBody$Outbound = {
  url?: string | undefined;
  webhook?: string | undefined;
};

/** @internal */
export const RequestBody$outboundSchema: z.ZodType<
  RequestBody$Outbound,
  z.ZodTypeDef,
  RequestBody
> = z.object({
  url: z.string().optional(),
  webhook: Webhook$outboundSchema.optional(),
});

export function requestBodyToJSON(requestBody: RequestBody): string {
  return JSON.stringify(RequestBody$outboundSchema.parse(requestBody));
}

/** @internal */
export const SubscribeToWebhooksResponse$inboundSchema: z.ZodType<
  SubscribeToWebhooksResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  Error: shared.ErrorT$inboundSchema.optional(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "Error": "error",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
  });
});

export function subscribeToWebhooksResponseFromJSON(
  jsonString: string,
): SafeParseResult<SubscribeToWebhooksResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SubscribeToWebhooksResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SubscribeToWebhooksResponse' from JSON`,
  );
}
