workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    bar-api:
        inputs:
            - location: https://raw.githubusercontent.com/speakeasy-api/openapi-reference-documentation/main/example/openapi.yaml
targets:
    bar-typescript:
        target: typescript
        source: bar-api
