workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    bar-api:
        inputs:
            - location: ./openapi.yaml
targets:
    bar-typescript:
        target: typescript
        source: bar-api
