workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    bar-api:
        inputs:
            - location: ./openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/speakeasy-team/speakeasy-team/speakeasy-bar-typescript
targets:
    bar-typescript:
        target: typescript
        source: bar-api
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/speakeasy-team/speakeasy-team/speakeasy-bar-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
