workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    bar-api:
        inputs:
            - location: ./openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/qynn/readme-editor-tests/bar-api
targets:
    bar-typescript:
        target: typescript
        source: bar-api
        publish:
            npm:
                token: $npm_token
